import type { SessionHistory } from "../src/lib/schema"

export const replayFixture: SessionHistory = {
  session: {
    id: "replay",
    status: "STOPPED",
    startedAt: "2026-09-01T12:00:00Z",
    endedAt: "2026-09-01T12:01:00Z",
    segmentTotal: 3,
    readyTotal: 2,
    costCny: 0,
  },
  segments: [1, 2, 3].map((sequence) => ({
    id: `clip-${sequence}`,
    sequence,
    startSeconds: (sequence - 1) * 2,
    endSeconds: sequence * 2,
    status: sequence === 2 ? "FAILED" : "READY",
    playable: sequence !== 2,
    direction: {
      action: `动作${sequence}`,
      dialogue: `台词${sequence}`,
      emotion: "calm",
      camera: { shot: "medium", movement: "fixed", angle: "front" },
      continuity: { notes: "" },
    },
  })),
  observerRuns: [],
}

export function replayVideo() {
  return Buffer.from(
    "GkXfo59ChoEBQveBAULygQRC84EIQoKEd2VibUKHgQJChYECGFOAZwEAAAAAAAQUEU2bdLpNu4tTq4QVSalmU6yBoU27i1OrhBZUrmtTrIHWTbuMU6uEElTDZ1OsggEyTbuMU6uEHFO7a1OsggP+7AEAAAAAAABZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVSalmsCrXsYMPQkBNgIxMYXZmNjMuMS4xMDFXQYxMYXZmNjMuMS4xMDFEiYhAn0AAAAAAABZUrmvXrgEAAAAAAABO14EBc8WIfnZAFMNFlz+cgQAitZyDdW5kiIEAhoVWX1ZQOIOBASPjg4QF9eEA4JCwgaC6gVqagQJVsIRVuYEBVe6BAOwBAAAAAAAAAgAAElTDZ/pzc59jwIBnyJlFo4dFTkNPREVSRIeMTGF2ZjYzLjEuMTAxc3PVY8CLY8WIfnZAFMNFlz9nyKBFo4dFTkNPREVSRIeTTGF2YzYzLjEuMTAxIGxpYnZweGfIoUWjiERVUkFUSU9ORIeTMDA6MDA6MDIuMDAwMDAwMDAwAB9DtnVCR+eBAKPWgQAAgPAFAJ0BKqAAWgAARwiFhYiFhIgCAgJ1qgP4AgaaE+CGqpNdxDqqTXcQ6qk13EOqpNdxDqqTXcQYAP7/TRL//FhX8WFfxYV/8WFf/PzO7cX85gCjmIEAZAARAgAFEKwAGAAYWC/0AAiAgQAAAKOYgQDIABECAAUQrAAYABhYL/QACICBAAAAo5iBASwAEQIABRCsABgAGFgv9AAIgIEAAACjmIEBkAARAgAFEKwAGAAYWC/0AAiAgQAAAKOYgQH0ABECAAUQrAAYABhYL/QACICBAAAAo5iBAlgAEQIABRCsABgAGFgv9AAIgIEAAACjl4ECvADxAQAFEBAUYABhYL/QACICBAAAo5iBAyAAEQIABRCsABgAGFgv9AAIgIEAAACjmIEDhAARAgAFEKwAGAAYWC/0AAiAgQAAAKOYgQPoABECAAUQrAAYABhYL/QACICBAAAAo5iBBEwAEQIABRCsABgAGFgv9AAIgIEAAACjmIEEsAARAgAFEKwAGAAYWC/0AAiAgQAAAKOYgQUUABECAAUQrAAYABhYL/QACICBAAAAo5iBBXgAEQIABRCsABgAGFgv9AAIgIEAAACjmIEF3AARAgAFEKwAGAAYWC/0AAiAgQAAAKOYgQZAABECAAUQrAAYABhYL/QACICBAAAAo5iBBqQAEQIABRCsABgAGFgv9AAIgIEAAACjl4EHCADxAQAFEBAUYABhYL/QACICBAAAo5iBB2wAEQIABRCsABgAGFgv9AAIgIEAAAAcU7trkbuPs4EAt4r3gQHxggGx8IED",
    "base64",
  )
}
