package main

import (
	"os"
	"path/filepath"
	"testing"
)

func TestSourceLines(t *testing.T) {
	for _, test := range []struct {
		name, source string
		want         int
	}{
		{"comments", "package p\n// comment\n/* block\ncomment */\nvar x = 1 // trailing\n\n", 2},
		{"strings", "package p\nvar x = `// not a comment\n\n/* still a string */`\n", 3},
		{"generated", "// Code generated by test. DO NOT EDIT.\npackage p\n", 0},
	} {
		t.Run(test.name, func(t *testing.T) {
			path := filepath.Join(t.TempDir(), "source.go")
			if err := os.WriteFile(path, []byte(test.source), 0600); err != nil {
				t.Fatal(err)
			}
			got, err := sourceLines(path)
			if err != nil || got != test.want {
				t.Fatalf("lines=%d err=%v, want %d", got, err, test.want)
			}
		})
	}
}
